# Generated by Django 4.2.8 on 2025-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'tbl_roles',
            },
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('google_calendar_id', models.CharField(blank=True, default='primary', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ManyToManyField(to='pub.roles')),
            ],
            options={
                'db_table': 'tbl_staffs',
            },
        ),
    ]
