# Generated by Django 4.2.8 on 2025-05-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='staff_id',
            new_name='role_id',
        ),
    ]
