# Generated by Django 4.2.8 on 2025-05-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0003_tasks_assignments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignments',
            table='tbl_assignments',
        ),
    ]
