# Generated by Django 4.2.8 on 2025-06-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0005_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(choices=[('OBS', 'Observance'), ('COV', 'Coverage')], max_length=3),
        ),
    ]
