# Generated by Django 4.2.8 on 2025-06-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0006_alter_tasks_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='WORKING', max_length=20),
        ),
    ]
