# Generated by Django 4.2.8 on 2025-06-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0007_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('PENDING', 'Pending'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='WORKING', max_length=20),
        ),
    ]
