# Generated by Django 4.2.8 on 2025-06-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0009_tasks_google_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='notes',
        ),
    ]
