# Generated by Django 4.2.8 on 2025-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0010_remove_assignments_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(choices=[('OBS', 'Observance'), ('COV', 'Coverage'), ('SEG', 'Segment')], max_length=3),
        ),
    ]
