# Generated by Django 4.2.8 on 2026-08-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0011_alter_tasks_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='google_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tasks',
            name='google_sync_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
