"""
Django settings for pubmanager project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit

# Use PyMySQL as the MySQL driver (pure Python, works on Vercel without C deps)
import pymysql
pymysql.install_as_MySQLdb()
import certifi

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-%7+rhy-rnj$_k&a7z#@k!#v_+%218qwmi#l!e2!l$ir^a_-z0#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
	'pub.apps.PubConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pubmanager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pubmanager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


def build_database_config(database_url):
    """Build a Django MySQL config from a mysql:// URL.

    Remote TiDB/Vercel URLs often include query params like sslmode=require,
    which are not valid kwargs for the MySQL Python connector. Strip those
    unsupported options and keep the TLS config in the supported ssl dict.
    """

    fallback = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'pubmanager_db',
            'PORT': '3307',
            'USER': 'root',
            'PASSWORD': '',
        }
    }

    if not database_url:
        return fallback

    parsed = urlsplit(database_url)
    if parsed.scheme not in {'mysql', 'mysql+mysqlconnector', 'mysql+pymysql'}:
        return fallback

    host = parsed.hostname or 'localhost'
    db_name = parsed.path.lstrip('/') or 'pubmanager_db'
    user = unquote(parsed.username or '')
    password = unquote(parsed.password or '')
    port = parsed.port or 3306

    config = {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': db_name,
        'USER': user,
        'PASSWORD': password,
        'HOST': host,
        'PORT': port,
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }

    query_params = parse_qs(parsed.query, keep_blank_values=True)
    ssl_values = {}
    for key in ('ca', 'cert', 'key'):
        value = query_params.get(f'ssl-{key}') or query_params.get(f'ssl_{key}')
        if value:
            ssl_values[key] = value[0]

    if host not in {'localhost', '127.0.0.1'}:
        ssl_values.setdefault('ca', certifi.where())

    if ssl_values:
        config['OPTIONS']['ssl'] = ssl_values

    return {'default': config}


DATABASE_URL = os.environ.get('DATABASE_URL', '')
DATABASES = build_database_config(DATABASE_URL)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'pub' / 'static']
STATICFILES_EXCLUDES = ['css/input.css']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Security for production behind proxy (Vercel)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/calendar/'  # or your desired default page